# -*- coding: utf-8 -*-
"""Project 3.0-Multiplication Table.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TW4Hq3qeUBwwEhNAvRq7k9CNhj7BiM2C

##**Project 03 - Multiplication Table**
"""

num = int(input("Enter the No to print the table of: "))
row = int(input("End No: "))
print("\nMultiplication Table of {num}:\n")
i = 1

#While loop
while i <= row:
    # Using f-strings for formatted printing 
    print(f'{num} * {i} = {num * i}')
    i += 1

