# -*- coding: utf-8 -*-
"""Project 2.0:RockPaperScissor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IP0kkHr0G5HhHqMYRzkBy_3CHhps0YH7

# **Rock,Paper and Scissors**
"""

#user input
print("\t\t\tLets paly Rock, Paper and Scissors\n ")
print("")
player1 = str(input("Choose b/w r/p/s [Rock, Paper or Scissors] \n"))
player2 = str(input("Choose b/w r/p/s [Rock, Paper or Scissors] \n"))

#logic using conditional checks

#logic for rock
if (player1=='r') and (player2=='r'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("No one scored. It's a tie")
elif (player1=='r') and (player2=='p'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player2 has won the game")
elif (player1=='r') and (player2=='s'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player1 has won the game")

#logic for paper
elif (player1=='p') and (player2=='r'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player1 has won the game")
elif (player1=='p') and (player2=='p'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("No one scored. It's a tie")
elif (player1=='p') and (player2=='s'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player2 has won the game")

#logic for scissior
elif (player1=='s') and (player2=='r'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player1 has won the game")
elif (player1=='s') and (player2=='p'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("Player2 has won the game")
elif (player1=='s') and (player2=='s'):
  print("Player choose {option} and Player2 choose {option2}".format(option=player1, option2=player2))
  print("No one scored. It's a tie ")

else:
  print("Your choosed wrong option! Try again")