# -*- coding: utf-8 -*-
"""Project 1.0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAj7cE9uj7z-WmapYJyEs3nhJBPPrtaV

# **Student Portfolio**
Name of the Student,
Class/Std,
Roll no,
Computer Science,
English,
Kannada,
Total,
Percent
"""

name=input("Enter Name of the Student : ")
std=input("Enter Student Class/Std : ")
rollno=int(input("Enter Student Roll No : "))  #type only integer
sub1=int(input("\nEnter Computer Science : "))
sub2=int(input("Enter English : "))
sub3=int(input("Enter Kannada : "))

print("\nName             : ",name)
print("Class/Std        : ",std)
print("Roll No          : ",rollno)
print("Computer Science : ",sub1)
print("English          : ",sub2)
print("Kannada          : ",sub2)
total=sub1+sub2+sub3
print("Total Marks      : ",total)

percentage = total/300*100
print("Percentage       : ", percentage)

